<script setup>
import { watch,ref } from 'vue';
import { api,errorMessage } from '../api';
const props=defineProps({kind:String});const rows=ref([]),page=ref(1),last=ref(1),error=ref(''),busy=ref(false);
async function load(){busy.value=true;error.value='';try{const {data}=await api.get('/admin/'+props.kind,{params:{page:page.value}});rows.value=data.data;last.value=data.last_page;}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function update(row,status){try{await api.patch(`/admin/${props.kind}/${row.id}`,props.kind==='reservations'?{status}:{});await load();}catch(e){error.value=errorMessage(e);}}
watch(()=>props.kind,()=>{page.value=1;load();},{immediate:true});
</script>
<template><div class="admin-page-heading"><div><span class="eyebrow">KEEP IN TOUCH</span><h1>{{ kind==='reservations' ? 'Table reservations' : 'Customer messages' }}</h1></div></div><p v-if="error" class="form-error" role="alert">{{ error }}</p><p v-if="busy">Loading…</p><div v-else class="inbox-list"><article v-for="row in rows" :key="row.id" class="panel"><div class="section-heading"><h2>{{ row.name }}</h2><span class="status-badge">{{ kind==='reservations' ? row.status : row.read_at ? 'Read' : 'Unread' }}</span></div><template v-if="kind==='reservations'"><p>{{ row.date.slice(0,10) }} · {{ row.time }} · {{ row.guests }} guests</p><a :href="'tel:'+row.phone">{{ row.phone }}</a><div class="inline-actions"><button v-for="status in ['pending','confirmed','cancelled']" :key="status" class="button button-outline" :disabled="status===row.status" @click="update(row,status)">{{ status }}</button></div></template><template v-else><a :href="'mailto:'+row.email">{{ row.email }}</a><p class="message-body">{{ row.message }}</p><button v-if="!row.read_at" class="button button-outline" @click="update(row)">Mark as read</button></template></article><div v-if="!rows.length" class="panel empty-state">Your inbox is clear.</div></div><div v-if="last>1" class="pagination"><button :disabled="page===1" @click="page--;load()">Previous</button><span>{{ page }} / {{ last }}</span><button :disabled="page===last" @click="page++;load()">Next</button></div></template>
