<script setup>
import { onMounted,onUnmounted,ref } from 'vue';
import { useRouter } from 'vue-router';
import { api,errorMessage } from '../api';
import { settings,user,logout,notify } from '../store';
const router=useRouter();const menuOpen=ref(false);const unread=ref(0);const soundEnabled=ref(false);let audio;
const links=[['','Overview','◈'],['orders','Orders','▤'],['categories','Categories','▦'],['products','Food menu','♨'],['deals','Deals','✦'],['customers','Customers','♙'],['coupons','Coupons','%'],['delivery-areas','Delivery areas','↗'],['payments','Payments','▣'],['reports','Reports','▥'],['reservations','Reservations','◷'],['messages','Messages','✉'],['notifications','Notifications','♧'],['settings','Settings','⚙']];
async function checkNotifications(){try{const {data}=await api.get('/notifications');if(soundEnabled.value && data.unread_count>unread.value && audio){const oscillator=audio.createOscillator();const gain=audio.createGain();oscillator.connect(gain);gain.connect(audio.destination);gain.gain.value=.06;oscillator.frequency.value=660;oscillator.start();oscillator.stop(audio.currentTime+.2);}unread.value=data.unread_count;}catch{}}
async function enableSound(){try{audio ||= new (window.AudioContext || window.webkitAudioContext)();await audio.resume();soundEnabled.value=!soundEnabled.value;}catch{notify('Sound is unavailable in this browser.');}}
async function signOut(){try{await logout();await router.push('/admin/login');}catch(error){notify(errorMessage(error));}}
onMounted(checkNotifications);const timer=setInterval(checkNotifications,15000);onUnmounted(()=>{clearInterval(timer);audio?.close();});
</script>
<template><div class="admin-shell"><aside class="admin-sidebar" :class="{open:menuOpen}"><router-link to="/admin" class="brand"><span class="brand-icon">♨</span>{{ settings.name }}</router-link><span class="sidebar-caption">RESTAURANT WORKSPACE</span><nav aria-label="Administration navigation"><router-link v-for="[path,label,icon] in links" :key="path" :to="`/admin${path ? '/'+path : ''}`" :exact="!path" @click="menuOpen=false"><span>{{ icon }}</span>{{ label }}<small v-if="path==='notifications' && unread">{{ unread }}</small></router-link></nav><router-link class="back-to-store" to="/">← Visit restaurant</router-link><button class="sidebar-signout" @click="signOut">Sign out</button></aside><div class="admin-body"><header class="admin-topbar"><button class="admin-menu-toggle" @click="menuOpen=!menuOpen" aria-label="Toggle admin navigation" :aria-expanded="menuOpen">☰</button><div><span class="eyebrow">THE BUSINESS OF GOOD FOOD</span><strong>Your restaurant, in one place.</strong></div><div class="admin-top-actions"><button @click="enableSound" class="text-button">{{ soundEnabled ? 'Sound on ♫' : 'Enable order sound' }}</button><router-link to="/admin/notifications">Updates <span class="count-badge">{{ unread }}</span></router-link><span class="admin-avatar">{{ user?.name.slice(0,1) }}</span></div></header><div class="admin-content"><router-view /></div></div></div></template>
