<script setup>
import { ref,onMounted,watch,onUnmounted } from 'vue';
import { api,errorMessage } from '../api';
import { money,statusLabel } from '../store';
const orders=ref([]);const error=ref('');const busy=ref(false);const status=ref('');const search=ref('');const page=ref(1);const lastPage=ref(1);
const statuses=['pending','confirmed','preparing','ready','out_for_delivery','delivered','completed','cancelled'];
async function load(){busy.value=true;error.value='';try{const {data}=await api.get('/admin/orders',{params:{status:status.value || undefined,search:search.value || undefined,page:page.value}});orders.value=data.data;lastPage.value=data.meta.last_page;}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
watch(status,()=>{page.value=1;load();});onMounted(load);const timer=setInterval(()=>{if(!busy.value)load();},20000);onUnmounted(()=>clearInterval(timer));
</script>
<template><div><div class="admin-page-heading"><div><div class="eyebrow">FROM THE FIRST CLICK TO THE LAST BITE</div><h1>Orders</h1><p>Confirm, prepare, and keep every customer in the loop.</p></div><button class="button button-small" @click="load" :disabled="busy">Refresh ↻</button></div><div v-if="error" class="form-error" role="alert">{{ error }}</div><div class="panel"><form class="admin-list-toolbar" @submit.prevent="page=1;load()"><label class="search-field"><span>⌕</span><input v-model="search" placeholder="Order number or customer…" aria-label="Search orders"></label><label class="status-filter">Status<select v-model="status"><option value="">All orders</option><option v-for="item in statuses" :key="item" :value="item">{{ statusLabel(item) }}</option></select></label><button class="text-button">Search →</button></form><div class="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Type</th><th>Total</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="order in orders" :key="order.id"><td><router-link :to="`/admin/orders/${order.id}`" class="table-order-number">{{ order.order_number }}</router-link><small>{{ new Date(order.created_at).toLocaleString() }}</small></td><td>{{ order.customer_name }}<small>{{ order.customer_phone }}</small></td><td>{{ statusLabel(order.order_type) }}</td><td>{{ money(order.total) }}</td><td>{{ statusLabel(order.payment_status) }}</td><td><span class="status-badge" :data-status="order.order_status">{{ statusLabel(order.order_status) }}</span></td><td><router-link :to="`/admin/orders/${order.id}`" class="text-button">Manage →</router-link></td></tr><tr v-if="!orders.length"><td colspan="7">{{ busy ? 'Loading orders…' : 'No orders match your filters.' }}</td></tr></tbody></table></div><div class="pagination"><button :disabled="page<=1 || busy" @click="page--;load()">← Previous</button><span>{{ page }} / {{ lastPage }}</span><button :disabled="page>=lastPage || busy" @click="page++;load()">Next →</button></div></div></div></template>
