<script setup>
import { onMounted,ref } from 'vue';
import { api,errorMessage } from '../api';
import { money,statusLabel } from '../store';
const payments=ref([]);const page=ref(1);const lastPage=ref(1);const error=ref('');const busy=ref(false);
async function load(){busy.value=true;try{const {data}=await api.get('/admin/payments',{params:{page:page.value}});payments.value=data.data;lastPage.value=data.last_page;error.value='';}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
onMounted(load);
</script>
<template><div><div class="admin-page-heading"><div><div class="eyebrow">EVERY PAYMENT, ACCOUNTED FOR</div><h1>Payments</h1><p>Cash payment records. Open an order to record receipt or a refund.</p></div><button class="button button-small" @click="load" :disabled="busy">Refresh ↻</button></div><div v-if="error" class="form-error" role="alert">{{ error }}</div><div class="panel"><div class="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Method</th><th>Amount</th><th>Status</th><th>Paid at</th><th></th></tr></thead><tbody><tr v-for="payment in payments" :key="payment.id"><td class="table-order-number">{{ payment.order.order_number }}</td><td>{{ payment.order.customer_name }}</td><td>{{ statusLabel(payment.payment_method) }}</td><td>{{ money(payment.amount) }}</td><td><span class="status-badge" :data-status="payment.payment_status==='paid' ? 'completed' : payment.payment_status==='refunded' ? 'cancelled' : 'pending'">{{ statusLabel(payment.payment_status) }}</span></td><td>{{ payment.paid_at ? new Date(payment.paid_at).toLocaleString() : '—' }}</td><td><router-link class="text-button" :to="`/admin/orders/${payment.order_id}`">Manage →</router-link></td></tr><tr v-if="!payments.length"><td colspan="7">No payments recorded yet.</td></tr></tbody></table></div><div class="pagination"><button :disabled="page<=1 || busy" @click="page--;load()">← Previous</button><span>{{ page }} / {{ lastPage }}</span><button :disabled="page>=lastPage || busy" @click="page++;load()">Next →</button></div></div></div></template>
