<script setup>
import { onMounted, reactive, ref } from 'vue';
import { api, errorMessage } from '../api';
import { loadConfiguration, notify } from '../store';
const form=reactive({opening_hours:[]});const loading=ref(true),busy=ref(false),error=ref('');const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
onMounted(async()=>{try{Object.assign(form,(await api.get('/admin/settings')).data.data);}catch(e){error.value=errorMessage(e);}finally{loading.value=false;}});
async function save(){busy.value=true;error.value='';try{await api.put('/admin/settings',form);await loadConfiguration();notify('Restaurant settings saved.');}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function upload(event){const file=event.target.files[0];if(!file)return;const body=new FormData();body.append('image',file);try{form.logo=(await api.post('/admin/images',body)).data.image;}catch(e){error.value=errorMessage(e);}}
</script>
<template><div class="admin-page-heading"><div><span class="eyebrow">MAKE IT YOURS</span><h1>Restaurant settings</h1><p>Opening hours and charges apply immediately to new orders.</p></div></div><p v-if="error" class="form-error" role="alert">{{ error }}</p><p v-if="loading">Loading settings…</p><form v-else @submit.prevent="save" class="panel settings-form"><h2>Restaurant details</h2><div class="form-grid"><label>Restaurant name<input v-model="form.name" required maxlength="100"></label><label>Phone<input v-model="form.phone"></label><label>Email<input v-model="form.email" type="email"></label><label>Logo URL<input v-model="form.logo" placeholder="https:// or /storage/"></label><label>Upload logo<input type="file" accept="image/jpeg,image/png,image/webp" @change="upload"></label><label class="full-width">Address<textarea v-model="form.address" rows="2"></textarea></label></div><h2>Ordering & charges</h2><div class="form-grid"><label>Currency<select v-model="form.currency"><option v-for="code in ['PKR','USD','GBP','AED']" :key="code">{{ code }}</option></select></label><label>Time zone<input v-model="form.timezone" required placeholder="Asia/Karachi"></label><label>Minimum delivery order<input v-model="form.minimum_order" type="number" min="0" step="0.01" required></label><label>Default delivery charge<input v-model="form.delivery_charge" type="number" min="0" step="0.01" required></label><label>Tax percentage<input v-model="form.tax_percentage" type="number" min="0" max="100" step="0.01" required></label><label class="checkbox-label"><input v-model="form.accepting_orders" type="checkbox">Accept new orders</label></div><h2>Weekly opening hours</h2><p>Times use the restaurant’s time zone. Equal opening and closing times mean 24 hours; a closing time before opening continues overnight.</p><div v-for="(hours,index) in form.opening_hours" :key="index" class="hours-editor"><label class="checkbox-label"><input v-model="hours.enabled" type="checkbox">{{ days[index] }}</label><label>Opens<input v-model="hours.open" type="time" required></label><label>Closes<input v-model="hours.close" type="time" required></label></div><button class="button" :disabled="busy">{{ busy ? 'Saving…' : 'Save settings' }}</button></form></template>
