<script setup>
import { onMounted,ref } from 'vue';
import { api,errorMessage } from '../api';
import { money } from '../store';
const customers=ref([]);const page=ref(1);const lastPage=ref(1);const search=ref('');const error=ref('');const busy=ref(false);
async function load(){busy.value=true;try{const {data}=await api.get('/admin/customers',{params:{page:page.value,search:search.value || undefined}});customers.value=data.data;lastPage.value=data.last_page;error.value='';}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
async function toggle(customer){busy.value=true;try{await api.patch(`/admin/customers/${customer.id}`,{is_active:!customer.is_active});await load();}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
onMounted(load);
</script>
<template><div><div class="admin-page-heading"><div><div class="eyebrow">THE PEOPLE AROUND YOUR TABLE</div><h1>Customers</h1><p>View your community and manage account availability.</p></div></div><div v-if="error" class="form-error" role="alert">{{ error }}</div><div class="panel"><form class="admin-list-toolbar" @submit.prevent="page=1;load()"><label class="search-field"><span>⌕</span><input v-model="search" placeholder="Name or email…" aria-label="Search customers"></label><button class="text-button">Search →</button></form><div class="table-scroll"><table><thead><tr><th>Customer</th><th>Phone</th><th>Orders</th><th>Fulfilled sales</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="customer in customers" :key="customer.id"><td><strong>{{ customer.name }}</strong><small>{{ customer.email }}</small></td><td>{{ customer.phone || '—' }}</td><td>{{ customer.orders_count }}</td><td>{{ money(customer.orders_sum_total) }}</td><td><span class="status-badge" :data-status="customer.is_active ? 'confirmed' : 'cancelled'">{{ customer.is_active ? 'Active' : 'Disabled' }}</span></td><td><button class="text-button" @click="toggle(customer)" :disabled="busy">{{ customer.is_active ? 'Disable account' : 'Enable account' }}</button></td></tr><tr v-if="!customers.length"><td colspan="6">No customers found.</td></tr></tbody></table></div><div class="pagination"><button :disabled="page<=1 || busy" @click="page--;load()">← Previous</button><span>{{ page }} / {{ lastPage }}</span><button :disabled="page>=lastPage || busy" @click="page++;load()">Next →</button></div></div></div></template>
