<script setup>
import { onMounted, reactive, ref } from 'vue';
import { api, errorMessage } from '../api';
import { user } from '../store';
const addresses = ref([]); const editing = ref(null); const formOpen = ref(false); const busy = ref(false); const error = ref('');
const defaults = () => ({label:'Home',address:'',city:'Lahore',area:'',landmark:'',phone:user.value?.phone || '',is_default:false});
const form = reactive(defaults());
async function load() {try {addresses.value=(await api.get('/addresses')).data.data;}catch(failure){error.value=errorMessage(failure);}}
function edit(address = null) {editing.value=address?.id || null;Object.assign(form,address ? {...address} : defaults());formOpen.value=true;error.value='';}
async function save() {busy.value=true;error.value='';try {await api[editing.value ? 'put' : 'post'](editing.value ? `/addresses/${editing.value}` : '/addresses',form);formOpen.value=false;await load();}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
async function remove(address) {busy.value=true;try{await api.delete(`/addresses/${address.id}`);await load();}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
onMounted(load);
</script>
<template><div class="panel"><div class="section-heading"><h2>Your addresses</h2><button class="button button-small" @click="edit()">Add address +</button></div><div v-if="error" class="form-error" role="alert">{{ error }}</div><form v-if="formOpen" class="form-grid inset-form" @submit.prevent="save"><label>Label<input v-model="form.label" required maxlength="50"></label><label>Phone<input v-model="form.phone" type="tel" pattern="[+0-9 ()-]{7,20}" required></label><label class="full-width">Address<textarea v-model="form.address" required maxlength="500"></textarea></label><label>City<input v-model="form.city" required maxlength="100"></label><label>Area<input v-model="form.area" required maxlength="100"></label><label class="full-width">Landmark<input v-model="form.landmark" maxlength="150"></label><label class="check-label full-width"><input v-model="form.is_default" type="checkbox"> Use as my default address</label><div class="row-actions full-width"><button class="button" :disabled="busy">{{ busy ? 'Saving…' : 'Save address' }}</button><button type="button" class="text-button" @click="formOpen=false">Cancel</button></div></form><div class="address-grid"><article v-for="address in addresses" :key="address.id" class="address-card"><div class="section-heading"><h3>{{ address.label }}</h3><span v-if="address.is_default" class="status-badge">Default</span></div><p>{{ address.address }}<br>{{ address.area }}, {{ address.city }}<br>{{ address.phone }}<br>{{ address.landmark }}</p><div class="row-actions"><button class="text-button" @click="edit(address)">Edit</button><button class="text-button accent" @click="remove(address)" :disabled="busy">Remove</button></div></article></div><p v-if="!addresses.length && !formOpen">Add your home or office to make checkout quicker.</p></div></template>
