<script setup>
import { computed, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import CartItems from '../components/CartItems.vue';
import { api,errorMessage } from '../api';
import { cartCount, cartPayload, cartItems, subtotal, money, user, deliveryAreas, settings } from '../store';
const router=useRouter();const type=ref('delivery');const area=ref(deliveryAreas.value[0]?.id || '');const coupon=ref('');const appliedCoupon=ref('');const quote=ref(null);const error=ref('');const busy=ref(false);
const fee=computed(()=>type.value === 'pickup' ? 0 : Number(deliveryAreas.value.find(item=>item.id === Number(area.value))?.fee ?? settings.delivery_charge));
const total=computed(()=>quote.value?.total ?? subtotal.value+fee.value);
watch([subtotal,type,area],()=>{quote.value=null;appliedCoupon.value='';});
async function applyCoupon(){if(!user.value){router.push('/login?redirect=/cart');return;}busy.value=true;error.value='';try{quote.value=(await api.post('/orders/quote',{items:cartPayload(),order_type:type.value,delivery_area_id:area.value,coupon_code:coupon.value})).data.data;appliedCoupon.value=quote.value.coupon_code || '';}catch(failure){error.value=errorMessage(failure);quote.value=null;appliedCoupon.value='';}finally{busy.value=false;}}
function checkout(){router.push({path:'/checkout',query:{type:type.value,area:area.value,coupon:appliedCoupon.value || undefined}});}
</script>
<template><section class="container section-space"><div class="page-heading"><div class="eyebrow">GOOD CHOICES, ALL AROUND</div><h1>Your bag of <span class="serif accent">happiness.</span></h1><p>{{ cartCount }} {{ cartCount===1 ? 'item' : 'items' }} ready to make your day.</p></div><div v-if="cartCount" class="cart-layout"><div><div v-if="cartItems.some(item=>!item.available)" class="form-error">Some dishes or extras are no longer available. Remove them before checkout.</div><CartItems /></div><aside class="order-summary"><h3>A delicious little summary</h3><div class="form-grid"><label class="full-width">Order type<select v-model="type"><option value="delivery">Home delivery</option><option value="pickup">Self pickup</option></select></label><label v-if="type==='delivery'" class="full-width">Delivery area<select v-model="area"><option value="" disabled>Select an area</option><option v-for="item in deliveryAreas" :key="item.id" :value="item.id">{{ item.name }}, {{ item.city }}</option></select></label></div><form class="coupon-form" @submit.prevent="applyCoupon"><label>Coupon code<input v-model="coupon" placeholder="WELCOME20" maxlength="50"></label><button :disabled="busy" type="submit">Apply</button></form><div v-if="error" class="form-error" role="alert">{{ error }}</div><div><span>Subtotal</span><strong>{{ money(subtotal) }}</strong></div><div><span>Delivery{{ !quote ? ' (estimate)' : '' }}</span><strong>{{ money(quote?.delivery_fee ?? fee) }}</strong></div><div v-if="quote?.discount"><span>Discount · {{ appliedCoupon }}</span><strong>− {{ money(quote.discount) }}</strong></div><div v-if="quote?.tax"><span>Tax</span><strong>{{ money(quote.tax) }}</strong></div><div class="summary-total"><span>{{ quote ? 'Total' : 'Estimated total' }}</span><strong>{{ money(total) }}</strong></div><p v-if="type==='delivery' && subtotal<Number(settings.minimum_order)">Add {{ money(Number(settings.minimum_order)-subtotal) }} more for delivery, or choose pickup.</p><button class="button" @click="checkout" :disabled="busy || cartItems.some(item=>!item.available) || (type==='delivery' && subtotal<Number(settings.minimum_order))">Continue to checkout →</button><p>Final totals are checked at checkout.</p><router-link to="/menu" class="text-button">Keep exploring ↗</router-link></aside></div><div v-else class="empty-state"><span>♨</span><h2>Something delicious is waiting.</h2><p>Your bag is empty. Let’s change that.</p><router-link to="/menu" class="button">Explore the menu ↗</router-link></div></section></template>
