<script setup>
import { computed, nextTick, onUnmounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import ProductCard from '../components/ProductCard.vue';
import { categories, cacheProducts } from '../store';
import { api, errorMessage } from '../api';
const route=useRoute();const router=useRouter();
const category=ref(String(route.query.category || ''));const search=ref('');const sort=ref('popular');const page=ref(1);const lastPage=ref(1);const total=ref(0);const results=ref([]);const busy=ref(false);const error=ref('');const searchInput=ref(null);
const isDeals=computed(()=>route.path === '/deals');
let requestNumber=0;let timer;
async function load(){const request=++requestNumber;busy.value=true;error.value='';try{const {data}=await api.get('/products',{params:{category:category.value || undefined,search:search.value || undefined,sort:sort.value,page:page.value,deals:isDeals.value ? 1 : undefined}});if(request!==requestNumber)return;results.value=data.data;cacheProducts(data.data);lastPage.value=data.meta.last_page;total.value=data.meta.total;}catch(failure){if(request===requestNumber)error.value=errorMessage(failure);}finally{if(request===requestNumber)busy.value=false;}}
watch([category,search,sort,isDeals],()=>{page.value=1;clearTimeout(timer);timer=setTimeout(load,200);});
watch(()=>route.query.category,value=>{category.value=String(value || '');});
watch(()=>route.query.focus,async value=>{if(value === 'search'){await nextTick();searchInput.value?.focus();}},{immediate:true});
load();onUnmounted(()=>{clearTimeout(timer);requestNumber++;});
</script>
<template><section class="container menu-page section-space"><div class="page-heading"><div class="eyebrow">{{ isDeals ? 'MORE FLAVOR. A LITTLE LESS.' : 'FRESH FROM OUR KITCHEN' }}</div><h1>{{ isDeals ? 'Good food. Great' : 'Find your next' }} <span class="serif accent">{{ isDeals ? 'deals.' : 'favorite.' }}</span></h1><p>{{ isDeals ? 'Share a feast, find your combo, and make a little more of mealtime.' : 'A little something for every craving. Prepared fresh, just for you.' }}</p></div><div class="menu-toolbar"><div v-if="!isDeals" class="category-tabs" aria-label="Food categories"><button :class="{selected:!category}" :aria-pressed="!category" @click="category=''">All</button><button v-for="item in categories" :key="item.id" :class="{selected:category===item.slug}" :aria-pressed="category===item.slug" @click="category=item.slug">{{ item.name }}</button></div><label class="search-field"><span>⌕</span><input ref="searchInput" v-model="search" type="search" placeholder="Find something delicious…" aria-label="Search menu"></label></div><div class="menu-meta"><span>{{ busy ? 'Finding your favorites…' : `${total} delicious choices` }}</span><label>Sort by <select v-model="sort" aria-label="Sort menu"><option value="popular">Our favorites</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><div v-if="error" class="form-error" role="alert">{{ error }} <button @click="load">Try again</button></div><div v-if="results.length" class="product-grid" :aria-busy="busy"><ProductCard v-for="product in results" :key="product.id" :product="product" /></div><div v-else-if="!busy && !error" class="empty-state"><span>⌕</span><h2>{{ isDeals ? 'Fresh deals are coming soon.' : 'No dishes found' }}</h2><p>Try another search or explore all our favorites.</p><button v-if="search || category" class="button" @click="search='';category=''">Reset filters</button><router-link v-else to="/menu" class="button">Explore the menu ↗</router-link></div><div v-if="lastPage>1" class="pagination"><button :disabled="page<=1 || busy" @click="page--;load()">← Previous</button><span>{{ page }} / {{ lastPage }}</span><button :disabled="page>=lastPage || busy" @click="page++;load()">Next →</button></div></section></template>
