<script setup>
import { onMounted, reactive, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { api, errorMessage, updateCsrf } from '../api';
import { user } from '../store';
const route = useRoute();
const form = reactive({name:user.value?.name || '',email:user.value?.email || '',phone:user.value?.phone || '',current_password:'',password:'',password_confirmation:''});
const error = ref(''); const message = ref(''); const busy = ref(false);
watch(()=>route.path,()=>{error.value='';message.value='';});
async function save() {busy.value=true;error.value='';message.value='';try { if(route.path.endsWith('/password')) {const {data}=await api.put('/password',{current_password:form.current_password,password:form.password,password_confirmation:form.password_confirmation}); updateCsrf(data); message.value=data.message; form.current_password='';form.password='';form.password_confirmation='';} else {const {data}=await api.patch('/profile',{name:form.name,email:form.email,phone:form.phone}); user.value=data.user;message.value='Profile saved.';} }catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
</script>
<template><div class="panel"><h2>{{ route.path.endsWith('/password') ? 'Change password' : 'Your profile' }}</h2><p>{{ route.path.endsWith('/password') ? 'Use at least eight characters, including a letter and a number.' : 'A few details that make ordering easier.' }}</p><div v-if="error" class="form-error" role="alert">{{ error }}</div><div v-if="message" class="form-success" role="status">{{ message }}</div><form class="form-grid" @submit.prevent="save"><template v-if="route.path.endsWith('/password')"><label class="full-width">Current password<input v-model="form.current_password" type="password" autocomplete="current-password" required></label><label class="full-width">New password<input v-model="form.password" type="password" autocomplete="new-password" minlength="8" required></label><label class="full-width">Confirm new password<input v-model="form.password_confirmation" type="password" autocomplete="new-password" minlength="8" required></label></template><template v-else><label class="full-width">Name<input v-model="form.name" required maxlength="80" autocomplete="name"></label><label class="full-width">Email<input v-model="form.email" type="email" required autocomplete="email"></label><label class="full-width">Phone<input v-model="form.phone" type="tel" required pattern="[+0-9 ()-]{7,20}" autocomplete="tel"></label></template><button class="button" :disabled="busy">{{ busy ? 'Saving…' : 'Save changes' }}</button></form></div></template>
