<script setup>
import { onMounted, onUnmounted, reactive, ref } from 'vue';
import { api,errorMessage } from '../api';
import { settings } from '../store';
const emit=defineEmits(['close']);const dialog=ref(null);const complete=ref(false);const busy=ref(false);const error=ref('');const form=reactive({name:'',phone:'',date:'',time:'19:00',guests:2});
const minDate=new Intl.DateTimeFormat('en-CA',{timeZone:settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const previousFocus=document.activeElement;const previousOverflow=document.body.style.overflow;
onMounted(()=>{dialog.value.showModal();document.body.style.overflow='hidden';});onUnmounted(()=>{document.body.style.overflow=previousOverflow;previousFocus?.focus();});
async function submit(){busy.value=true;error.value='';try{await api.post('/reservations',form);complete.value=true;}catch(failure){error.value=errorMessage(failure);}finally{busy.value=false;}}
</script>
<template><dialog ref="dialog" class="reservation-modal" aria-labelledby="reservation-title" @cancel.prevent="emit('close')" @click="event=>{if(event.target===dialog)emit('close');}"><button class="modal-close" @click="emit('close')" aria-label="Close reservation">×</button><div v-if="complete" class="reservation-success"><div class="success-icon">✓</div><h2 id="reservation-title">A seat for <span class="serif accent">you.</span></h2><p>Your request for {{ form.guests }} guests on {{ form.date }} at {{ form.time }} has been sent.</p><p>The restaurant will contact you to confirm availability.</p><button class="button" @click="emit('close')">Lovely, thank you</button></div><form v-else @submit.prevent="submit"><div class="eyebrow">WE’LL SAVE YOU A SEAT</div><h2 id="reservation-title">Make a little <span class="serif accent">time.</span></h2><p>Good food tastes better together.</p><div v-if="error" class="form-error" role="alert">{{ error }}</div><div class="form-grid"><label class="full-width">Your name<input v-model="form.name" required maxlength="80" autocomplete="name" autofocus></label><label class="full-width">Phone number<input v-model="form.phone" type="tel" pattern="[+0-9 ()-]{7,20}" required autocomplete="tel"></label><label>Date<input v-model="form.date" type="date" :min="minDate" required></label><label>Time<input v-model="form.time" type="time" step="1800" required></label><label class="full-width">Your people<select v-model.number="form.guests"><option v-for="count in 8" :key="count" :value="count">{{ count }} {{ count===1 ? 'guest' : 'guests' }}</option></select></label></div><button class="button" :disabled="busy">{{ busy ? 'Sending…' : 'Request a table' }} ↗</button><small class="demo-note">Requests are confirmed by the restaurant. Times use {{ settings.timezone }}.</small></form></dialog></template>
